# Generated by Django 4.0.1 on 2022-01-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_realted', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('GSM', 'Global System for Mobile Communications'), ('CDMA', 'Code Division Multiple Access'), ('HSPA', 'High Speed Packet Access'), ('EVDO', 'Evolution-Data Optimized'), ('LTE', 'Long Term Evolution'), ('5G', '5G')], max_length=25)),
                ('model', models.CharField(max_length=120)),
                ('year', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/', verbose_name='Image')),
                ('colors', models.CharField(choices=[('Green', 'Green'), ('Gray', 'Gray'), ('Red', 'Red'), ('Purple', 'Purple'), ('White', 'White'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Olive', 'Olive'), ('Lavender', 'Lavender'), ('Graphite', 'Graphite')], max_length=20)),
                ('price', models.CharField(max_length=120)),
                ('os', models.CharField(max_length=120)),
                ('memory', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Sport', 'Sport'), ('Sandbox', 'Sandbox'), ('RTS', 'Real-time strategy'), ('FPS', 'Shooters'), ('MOBA', 'Multiplayer online battle arena'), ('RGP', 'Role-playing'), ('Adventure', 'Action-adventure'), ('Survive', 'Survival and horror'), ('Platformer', 'Platformer')], max_length=40)),
                ('series', models.CharField(max_length=120)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game/', verbose_name='Image')),
                ('price', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('year', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Image')),
                ('trim', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
