version: '3'
services:  
    web:
        build: .
        restart: "always"
        ports:
            - "8000:8000"
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code/
            - ./static/:/code/static/
            - ./media/:/code/media/
    frontend:
        build: ./frontend
        command: ["npm", "start"]
        volumes:
        - ./frontend:/app/frontend
        - node-modules:/app/frontend/node_modules
        ports:
        - "80:3000"
volumes:
  node-modules:


            
